# Generated by Django 6.0.3 on 2026-05-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
