# Generated by Django 6.0.3 on 2026-05-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_help_category_user_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('local', 'Local Community'), ('authorities', 'All Authorities'), ('specific', 'Select Authorities')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='target_authority',
            field=models.CharField(blank=True, choices=[('police', 'Police'), ('fire', 'Fire'), ('medical', 'Medical'), ('general', 'General')], max_length=20, null=True),
        ),
    ]
