# Generated by Django 6.0.3 on 2026-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('police', 'Police'), ('fire', 'Fire'), ('medical', 'Medical'), ('general', 'General'), ('global', 'Global Strategic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='target_authority',
            field=models.CharField(blank=True, choices=[('police', 'Police'), ('fire', 'Fire'), ('medical', 'Medical'), ('general', 'General'), ('global', 'Global Strategic')], max_length=20, null=True),
        ),
    ]
