# Generated by Django 6.0.3 on 2026-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_alert_category_alter_alert_target_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Emergency Alert', max_length=255),
        ),
    ]
