# Generated by Django 6.0.3 on 2026-05-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='category',
            field=models.CharField(choices=[('food', 'Food Support'), ('blood', 'Blood Donation'), ('volunteer', 'Volunteer Force'), ('medical', 'Medical Supplies'), ('clothing', 'Clothing & Essentials'), ('financial', 'Financial Aid'), ('other', 'Other Assistance')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contributions/'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='core.contribution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
